### ISSUE TITLE
Requiring does not working on the browser

### ISSUE THREAD

**Issue by ThariqS** [larsgw/citation.js#18]
NPM modules are often used in the frontend now and requiring citation-js in the frontend gives an error. It would be great if it was meant to be exported as a frontend module as well.

**Comment by larsgw** [comment]
I'm not really sure what you mean by frontend in this specific case. I use a [naive way](https://github.com/larsgw/citation.js/blob/master/src/citation-0.2.js#L2342-L2343) of checking whether something is used in either the browser or nodejs, and I should probably upgrade this. I can imagine this going wrong when it's both. Can you please post the error message you get, and maybe how you use it?

**Comment by larsgw** [comment]
Things like [this](https://github.com/substack/node-browserify#external-requires) aren't implemented yet, if that's what you meant, but I'm working on it (#24).

**Comment by ThariqS** [comment]
A couple of things:
- https://github.com/larsgw/citation.js/blob/master/src/citation-0.2.js#L2585 doesn't seem to make sense and crashes
- The entry point is listed as: https://github.com/larsgw/citation.js/blob/master/index.js which requires 'fs' in the main scope (not available in the browser) so requiring citation.js directly will not work, someone would have to  `require('citation-js/src/citation-0.2)`

**Comment by larsgw** [comment]
Right, so I'll fix the first thing in `v0.3` anyway, together with all the other things I need to do to make it run better on both Node.js and in the browser, and mainly on Node.js *in* the browser, as that's not explicitly supported yet at all. The second point will probably be fixed in `v0.3` too, but I'll have to figure out how exactly first. I could put a `cli.js` for command-line support somewhere, or a browserify `bundle.js` for browser support. I'll probably do both actually, and make `require()` behaviour work as expected.

**Note:** `v0.3` may take some time. I'm not sure when I'll have enough time to finish it, but I'll try to publish prereleases in the meantime.

**Comment by larsgw** [comment]
It should now work with `v0.3.0-0`. I separated the CLI from the main thing, so that's not a problem anymore. If it doesn't, please do tell.

**Comment by larsgw** [comment]
Well, `v0.3.0-0` is broken (see #30), but the next version should work.

**Comment by larsgw** [comment]
It should work now (since `v0.3.0-2` from Mar 14, 2017), so I'm going to close the issue. If you still have an issue, please feel free to reopen (with some more information, as it works on my setup).
