### ISSUE TITLE
What does citation JS use to escape citation data before turning it into html?

### ISSUE THREAD

**Issue by J-avery32** [larsgw/citation.js#218]
And where can I see the code that does the actual escaping?

**Comment by larsgw** [comment]
That's a good question.

  - Formatted citation output (i.e. CSL output, `'bibliography'` and `'citation'`) is made with [citeproc-js](https://github.com/Juris-M/citeproc-js) and [its HTML escape function can be seen here](https://github.com/Juris-M/citeproc-js/blob/aa2683f48fe23be459f4ed3be3960e2bb56203f0/src/formats.js#L23-L39). It also allows [some generic formatting HTML](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#html-like-formatting-tags).
  - JSON, YAML, BibTeX and RIS output (and any other specific formats I may be forgetting) seem safe to me, in the sense that it should not be interpreted as HTML at all.

There are also two situations where a non-HTML format is outputted with HTML markup (e.g. JSON with HTML indentation for if you do not want to use `<pre>` for some reason). This is the status on those:

  - HTML-formatted BibTeX output is escaped because the BibTeX values themselves are [escaped with this code (specifically `UNSAFE_UNICODE` and `escapeValue`)](https://github.com/citation-js/citation-js/blob/36b2987fe48da59c48eedcdbf220e283bd32b37b/packages/plugin-bibtex/src/output/value.js#L8-L37).
  - HTML-formatted JSON output is **not** escaped. This only happens if you run `.format('data', { type: 'html' })` or `.format('data', { format: 'html' })`. When those options are used a warning is normally logged, but the logger is currently silent by default.

Other output formats do not offer this kind of HTML-formatted output, but if they did they are unlikely to be escaped.

**Comment by J-avery32** [comment]
I see. Thank you. I didn't realize that the code for escaping is in another repository.
